### ISSUE TITLE
CAD source files

### ISSUE THREAD

**Issue by m4mmon** [al2k/STL-Naturebytes-Enclosures#1]
Hello,
I was trying to design something around the case, and if STL are fine for printing, it's just a dead result with no geometry semantics.
Is it possible to get any CAD files?

**Comment by m4mmon** [comment]
will do some reverse engineering

**Comment by al2k** [comment]
Hi m4mmon. We'll have a look for the STEP version and post that. It will be much easier than reverse engineering :)

**Comment by m4mmon** [comment]
ho yes :) thank you very much!
